package main

// Detector pattern extraction.
//
// Parses internal/detector/** with go/ast and emits site/js/detectors.js, the
// data the in-browser playground scanner uses. Each detector contributes its
// ID, default severity, Aho-Corasick keywords, and the regex pattern(s) its
// Scan method references. Go uses RE2 (no look-around / back-references), which
// is a clean subset of JavaScript's regex syntax, so the patterns port over;
// a small normalization step handles the few Go-specific tokens.

import (
	"encoding/json"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

type detPattern struct {
	Src   string `json:"src"`
	Flags string `json:"flags,omitempty"`
}

type detEntry struct {
	ID       string       `json:"id"`
	Severity string       `json:"severity"`
	Keywords []string     `json:"keywords"`
	Patterns []detPattern `json:"patterns"`
}

// Packages whose detection depends on logic the browser can't fa­ithfully
// reproduce (entropy gating, runtime-registered rules, test helpers).
var detectorSkipDirs = map[string]bool{
	"testutil": true,
	"custom":   true,
	"generic":  true,
}

var leadingFlagsRe = regexp.MustCompile(`^\(\?([imsU]+)\)`)

// buildDetectors extracts detector patterns and writes site/js/detectors.js.
// It returns the number of detectors emitted.
func buildDetectors(root, jsDir string) (int, error) {
	detRoot := filepath.Join(root, "internal", "detector")
	fset := token.NewFileSet()
	var entries []detEntry

	err := filepath.WalkDir(detRoot, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if detectorSkipDirs[d.Name()] {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		f, perr := parser.ParseFile(fset, path, nil, 0)
		if perr != nil {
			return fmt.Errorf("parse %s: %w", path, perr)
		}
		entries = append(entries, extractDetectors(f)...)
		return nil
	})
	if err != nil {
		return 0, fmt.Errorf("walk detectors: %w", err)
	}

	sort.Slice(entries, func(i, j int) bool { return entries[i].ID < entries[j].ID })

	data, err := json.MarshalIndent(entries, "", "  ")
	if err != nil {
		return 0, fmt.Errorf("marshal detectors: %w", err)
	}
	content := "// Generated by tools/site-build from internal/detector. Do not edit by hand.\n" +
		"window.LW_DETECTORS = " + string(data) + ";\n"
	if err := os.WriteFile(filepath.Join(jsDir, "detectors.js"), []byte(content), 0o644); err != nil {
		return 0, fmt.Errorf("write detectors.js: %w", err)
	}
	return len(entries), nil
}

func extractDetectors(f *ast.File) []detEntry {
	// Named regexp vars (name -> raw pattern) and every MustCompile literal in
	// the file (covers patterns declared inside slices, used as a fallback).
	varPat := map[string]string{}
	var filePats []string
	for _, decl := range f.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.VAR {
			continue
		}
		for _, spec := range gd.Specs {
			vs, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}
			for i, val := range vs.Values {
				if raw, ok := mustCompileExpr(val); ok && i < len(vs.Names) {
					varPat[vs.Names[i].Name] = raw
				}
			}
		}
	}
	ast.Inspect(f, func(n ast.Node) bool {
		if call, ok := n.(*ast.CallExpr); ok {
			if raw, ok := mustCompileExpr(call); ok {
				filePats = append(filePats, raw)
			}
		}
		return true
	})

	// Group the detector methods by receiver type.
	type methods struct{ id, kw, sev, scan *ast.FuncDecl }
	types := map[string]*methods{}
	getType := func(name string) *methods {
		if types[name] == nil {
			types[name] = &methods{}
		}
		return types[name]
	}
	for _, decl := range f.Decls {
		fd, ok := decl.(*ast.FuncDecl)
		if !ok || fd.Recv == nil || len(fd.Recv.List) == 0 {
			continue
		}
		rt := recvTypeName(fd.Recv.List[0].Type)
		if rt == "" {
			continue
		}
		switch fd.Name.Name {
		case "ID":
			getType(rt).id = fd
		case "Keywords":
			getType(rt).kw = fd
		case "Severity":
			getType(rt).sev = fd
		case "Scan":
			getType(rt).scan = fd
		}
	}

	var out []detEntry
	for _, m := range types {
		if m.id == nil {
			continue
		}
		id := returnStringLit(m.id)
		if id == "" {
			continue
		}
		entry := detEntry{ID: id, Severity: severityOf(m.sev), Keywords: stringLitsIn(m.kw)}
		if entry.Keywords == nil {
			entry.Keywords = []string{}
		}

		// Patterns this type's Scan references by name; fall back to every
		// pattern in the file (correct for single-detector multi-pattern files).
		var pats []string
		if m.scan != nil {
			ast.Inspect(m.scan, func(n ast.Node) bool {
				if ident, ok := n.(*ast.Ident); ok {
					if p, ok := varPat[ident.Name]; ok {
						pats = append(pats, p)
					}
				}
				return true
			})
		}
		if len(pats) == 0 {
			pats = filePats
		}

		seen := map[string]bool{}
		for _, p := range dedup(pats) {
			src, flags, ok := goToJSRegex(p)
			if !ok || seen[src+"\x00"+flags] {
				continue
			}
			seen[src+"\x00"+flags] = true
			entry.Patterns = append(entry.Patterns, detPattern{Src: src, Flags: flags})
		}
		if len(entry.Patterns) > 0 {
			out = append(out, entry)
		}
	}
	return out
}

// mustCompileExpr reports whether expr is regexp.MustCompile(`literal`) and
// returns the unquoted pattern.
func mustCompileExpr(expr ast.Expr) (string, bool) {
	call, ok := expr.(*ast.CallExpr)
	if !ok {
		return "", false
	}
	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok || sel.Sel.Name != "MustCompile" {
		return "", false
	}
	pkg, ok := sel.X.(*ast.Ident)
	if !ok || pkg.Name != "regexp" || len(call.Args) != 1 {
		return "", false
	}
	lit, ok := call.Args[0].(*ast.BasicLit)
	if !ok || lit.Kind != token.STRING {
		return "", false
	}
	s, err := strconv.Unquote(lit.Value)
	if err != nil {
		return "", false
	}
	return s, true
}

func recvTypeName(e ast.Expr) string {
	switch t := e.(type) {
	case *ast.StarExpr:
		return recvTypeName(t.X)
	case *ast.Ident:
		return t.Name
	}
	return ""
}

func returnStringLit(fd *ast.FuncDecl) string {
	if fd == nil || fd.Body == nil {
		return ""
	}
	var out string
	ast.Inspect(fd.Body, func(n ast.Node) bool {
		ret, ok := n.(*ast.ReturnStmt)
		if !ok || len(ret.Results) != 1 {
			return true
		}
		if lit, ok := ret.Results[0].(*ast.BasicLit); ok && lit.Kind == token.STRING {
			if s, err := strconv.Unquote(lit.Value); err == nil && out == "" {
				out = s
			}
		}
		return true
	})
	return out
}

func stringLitsIn(fd *ast.FuncDecl) []string {
	if fd == nil || fd.Body == nil {
		return nil
	}
	var out []string
	ast.Inspect(fd.Body, func(n ast.Node) bool {
		if lit, ok := n.(*ast.BasicLit); ok && lit.Kind == token.STRING {
			if s, err := strconv.Unquote(lit.Value); err == nil {
				out = append(out, s)
			}
		}
		return true
	})
	return out
}

func severityOf(fd *ast.FuncDecl) string {
	if fd == nil || fd.Body == nil {
		return "medium"
	}
	out := "medium"
	ast.Inspect(fd.Body, func(n ast.Node) bool {
		sel, ok := n.(*ast.SelectorExpr)
		if !ok {
			return true
		}
		if x, ok := sel.X.(*ast.Ident); ok && x.Name == "finding" && strings.HasPrefix(sel.Sel.Name, "Severity") {
			out = strings.ToLower(strings.TrimPrefix(sel.Sel.Name, "Severity"))
			return false
		}
		return true
	})
	return out
}

func dedup(in []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, s := range in {
		if !seen[s] {
			seen[s] = true
			out = append(out, s)
		}
	}
	return out
}

// goToJSRegex normalizes a Go RE2 pattern for JavaScript and reports whether it
// is safe to use. It lifts leading inline flags into JS flags, rewrites named
// groups and Go-only anchors, and rejects patterns needing Unicode property
// escapes (which would require the 'u' flag and change escaping semantics).
func goToJSRegex(p string) (src, flags string, ok bool) {
	if m := leadingFlagsRe.FindStringSubmatch(p); m != nil {
		for _, c := range m[1] {
			switch c {
			case 'i', 'm', 's':
				if !strings.ContainsRune(flags, c) {
					flags += string(c)
				}
			}
		}
		p = p[len(m[0]):]
	}
	p = strings.ReplaceAll(p, "(?P<", "(?<")
	p = strings.ReplaceAll(p, `\A`, "^")
	p = strings.ReplaceAll(p, `\z`, "$")
	p = strings.ReplaceAll(p, `\Z`, "$")
	if strings.Contains(p, `\p{`) || strings.Contains(p, `\P{`) || strings.Contains(p, "(?P=") {
		return "", "", false
	}
	return p, flags, true
}
